### ISSUE TITLE
multiple partType in outline

### ISSUE THREAD

**Issue by berger-n** [buda-base/xmltoldmigration#128]
(as seen in buda-base/public-digital-library#211)
[bdr:MW1KG8321_89F02B](http://purl.bdrc.io/resource/MW1KG8321_89F02B.ttl) has multiple `partType`:
```
   bdo:partType  bdr:PartTypeText , bdr:PartTypeVolume .
```

**Comment by eroux** [comment]
It's an interesting case, what happens here is a hash collision:

```cli
$ echo -n "O1KG83211KG51470" |md5sum
89f02b188f2c36d6b4406b0738bb01c2  -
$ echo -n "O1KG83211KG50154" |md5sum
89f02bfaeae71b31f51f7213c3394afd  -
```

we take the first 6 digits so that creates the problem. The good news is that this type of collision can only happen in one file (because the outline node IDs are prefixed with the instance ID), but we need to detect them.

**Comment by eroux** [comment]
should be fixed

**Comment by xristy** [comment]
why not use 16 instead of 6 or all 32?

**Comment by eroux** [comment]
Well, for these we control the colisions, the editor can use more digits to be sure to avoid them
