### ISSUE TITLE
what are entities in products?

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#130]
Currently we're putting instances in products, for instance:

```
bda:PR1CTC17  a  adm:Product ;
   adm:productHasWork  bdr:MW19974 , bdr:MW1AB1 , etc.
```

apart from the fact that `adm:productHasWork` should be renamed, I think that if we're in the perspective that the things in the products are really the electronic resources (which I think is quite accurate), we should but the `W` records there, not the `MW`. What do you think @xristy ?

**Comment by xristy** [comment]
So I guess the property should be: 
```
adm:productHasDigitalInstance
    a owl:ObjectProperty ;
    rdfs:domain adm:Product ;
    rdfs:range bdo:DigitalInstance ;
.
```
This includes `bdo:ImageInstance` and `bdo:EtextInstance`.

Curiously there is no definition for `adm:productHasWork` in the admin.ttl.

**Comment by eroux** [comment]
perfect, let's define this new `adm:productHasDigitalInstance`, I'll make the changes to xmltold tomorrow

**Comment by xristy** [comment]
done via [bbc316](https://github.com/buda-base/owl-schema/commit/bbc3167b035917d64b9ab09cd08e2a05a13109d4)
