### ISSUE TITLE
finding changes made by a script

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#132]
log entries with date "2017-01-24T15:53:54.908Z"  were made by a script, I'm sure we can find others, I suppose it's suspicious if changes in different records happen at the same milisecond

**Comment by xristy** [comment]
when an xquery script is run, the datetime is fixed at the time the script starts and does not change during the execution of the script regardless of how long the script runs or how many docs are touched

**Comment by eroux** [comment]
yes. An interesting exception (although I guess it's multiple calls of the same query?) is the sync script which has a log entry with a different timestamp for each imagegroup

**Comment by xristy** [comment]
The script, `/db/modules/admin/imagegroups-updater.xql`, is called once for each imagegroup that is synced so each imagegroup log entry will reflect a different time.

**Comment by eroux** [comment]
here are a few others:

- 2012-12-25T01:09:21.507000+00:00
- 2015-10-27T19:58:07.021000+00:00
- 2012-12-11T17:49:53.482000+00:00
- 2013-12-03T23:23:40.962000+00:00
- 2012-12-11T17:21:51.251000+00:00
- 2012-12-11T17:08:33.797000+00:00
- 2014-03-20T14:27:21.266000+00:00
- 2014-04-22T00:30:13.577000+00:00
- 2015-01-05T17:22:13.356000+00:00
- 2017-08-28T14:40:13.266000+00:00
- 2014-05-02T18:19:14.334000+00:00
- 2012-03-30T11:00:49.672000+00:00
- 2019-12-20T20:45:53.530000+00:00
- 2019-12-20T20:42:53.606000+00:00
- 2017-11-02T17:38:24.575000+00:00
- 2014-07-29T20:49:23.894000+00:00
- 2014-07-29T16:18:50.168000+00:00
- 2017-06-26T14:21:21.664000+00:00
- 2017-06-26T14:20:59.643000+00:00
- 2013-04-19T11:24:55.882000+00:00
- 2014-10-15T17:56:23.536000+00:00
- 2014-04-23T19:16:52.743000+00:00
- 2017-07-07T21:31:19.810000+00:00
- 2014-03-07T15:45:20.935000+00:00
- 2015-05-07T18:09:14.220000+00:00
- 2016-12-05T22:09:43.772000+00:00
- 2014-04-23T19:13:59.680000+00:00
- 2014-05-02T17:27:14.339000+00:00
- 2016-05-10T16:55:52.884000+00:00
- 2013-04-19T11:24:25.492000+00:00
- 2018-05-31T19:53:40.968000+00:00
- 2017-11-02T17:17:10.070000+00:00
