### ISSUE TITLE
moving GEBIS note to scanInfo

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#161]
some works such as W8LS73583 have a Bibliographic Note "image copy donated by Ken-GEBIS". It would be best to remove this and instead add a scanInfo saying something like "Scans kindly provided by the Great Enlightenment Buddhist Institute Society (GEBIS) in Canada, made from an original copy provided by BDRC."

@karmagongde do you think you could ask the librarians to do this for future catalog? (also @TBRC-pmench @JannTibetan if you have a better idea of wording don't hesitate)

**Comment by JannTibetan** [comment]
Yes, thank you for addressing this. I was intending to bring this up as well. Perhaps we can say:
"Scans kindly provided by the Great Enlightenment Buddhist Institute Society (GEBIS). The hardcopy original was furnished to them by BDRC."

**Comment by karmagongde** [comment]
@eroux @JannTibetan I just asked librarians to add Bibliographic Note for scanned images source to every work number in the future. And sent them the suggested note.

GEBIS images: Scans kindly provided by the Great Enlightenment Buddhist Institute Society (GEBIS). The hardcopy original was furnished to them by BDRC.

USAID images: Scanned or acquired in Tibetan areas of China by BDRC.

For other scanned images source: Scans kindly provided by ......

**Comment by eroux** [comment]
great, thanks!

**Comment by eroux** [comment]
https://library.bdrc.io/search?q=%22image%20copy%20donated%20by%20Ken-GEBIS%22&lg=en&t=Instance&f=asset,inc,tmp:hasOpen&s=closest%20matches%20forced&n=1 these should still be changed

**Comment by karmagongde** [comment]
I changed them.

**Comment by eroux** [comment]
ah, thanks! I can't see the change in scanInfo though (for instance on W8LS73680, W8LS73583, etc.) are you sure you saved the changes?

**Comment by karmagongde** [comment]
I changed the Bibliographic Note "image copy donated by Ken-GEBIS". to "Scans kindly provided by the Great Enlightenment Buddhist Institute Society (GEBIS) in Canada, made from an original copy provided by BDRC."

**Comment by eroux** [comment]
Ah I see thanks! Note to self: make sure this is migrated to scaninfo
