### ISSUE TITLE
How to delete spurious works?

### ISSUE THREAD

**Issue by tadhondup** [buda-base/xmltoldmigration#199]
I linked [these 2 versions](https://library.bdrc.io/show/bdr:WA0NGMCP54399?tabs=bdr:MW0NGMCP54043) of the Chojuk with [the main one](https://library.bdrc.io/show/bdr:WA0RT3216?s=q%3D%2522%25E0%25BD%2596%25E0%25BE%25B1%25E0%25BD%2584%25E0%25BC%258B%25E0%25BD%2586%25E0%25BD%25B4%25E0%25BD%2596%25E0%25BC%258B%25E0%25BD%25A6%25E0%25BD%25BA%25E0%25BD%2598%25E0%25BD%25A6%25E0%25BC%258B%25E0%25BD%2591%25E0%25BD%2594%25E0%25BD%25A0%25E0%25BD%25B2%25E0%25BC%258B%25E0%25BD%25A6%25E0%25BE%25A4%25E0%25BE%25B1%25E0%25BD%25BC%25E0%25BD%2591%25E0%25BC%258B%25E0%25BD%2594%25E0%25BC%258B%25E0%25BD%25A3%25E0%25BC%258B%25E0%25BD%25A0%25E0%25BD%2587%25E0%25BD%25B4%25E0%25BD%2582%25E0%25BC%258B%25E0%25BD%2594%2522~1%26lg%3Dbo%26t%3DWork%26s%3Dclosest%2520matches%26n%3D1) with [this PR](https://github.com/buda-base/xmltoldmigration/pull/200/commits/98c1c00f410a10d63f83fb485b172271ac33acf4), should the current work be deleted? If so how to do it?

**Comment by eroux** [comment]
It will be done automatically, no problem. For the NGMCP works/versions it might take a bit more time since they're imported differently, but you can include them in this list. Thanks for the PR, it's very useful !!
