### ISSUE TITLE
Can texts be using as a work?

### ISSUE THREAD

**Issue by tadhondup** [buda-base/xmltoldmigration#203]
[MW23703_3874](https://library.bdrc.io/show/bdr:MW23703_3874) only exists as texts like [this one](https://library.bdrc.io/show/bdr:MW23703_3874), should we use one of these IDs to create the work or is there a way to create a new work ID?
@ngawangtrinley

**Comment by eroux** [comment]
I'm not sure I understand, if I follow your first link, I see it's already associated to a work, WA0RT3219, why would you want to use another one?

**Comment by ngawangtrinley** [comment]
this was a misunderstanding
