### ISSUE TITLE
encoding issue in bdr:W22704_3352 ?

### ISSUE THREAD

**Issue by berger-n** [buda-base/xmltoldmigration#53]
there seems to be an encoding issue in http://purl.bdrc.io/resource/W22704_3352.ttl :

`"dbu ma'i skor/ (tsa锛�ngi)"@bo-x-ewts`

![image](https://user-images.githubusercontent.com/33383857/42387046-84817f8c-8141-11e8-8378-1161f09c35d5.png)

**Comment by berger-n** [comment]
same in http://library.bdrc.io/show/bdr:W22704_3292: 

![image](https://user-images.githubusercontent.com/33383857/42387974-485d9e34-8144-11e8-8cde-2e8a0ddeb749.png)

**Comment by eroux** [comment]
the encoding problem is in the [original data](https://www.tbrc.org/xmldoc?rid=O2DB75712)
