### ISSUE TITLE
odd migration of a T192

### ISSUE THREAD

**Issue by xristy** [buda-base/xmltoldmigration#56]
``bdr:T192`` seems to be migrated in an off manner. The _XML_ is:

    <t:topic xmlns:t="http://www.tbrc.org/models/topic#" RID="T192" status="released">
        <t:name lang="tibetan" encoding="extendedWylie">thob yig</t:name>
        <t:name lang="tibetan" encoding="extendedWylie">gsan yig</t:name>
        <t:name lang="english" encoding="native">record of teachings received</t:name>
    </t:topic>

The resulting _ttl_ is:

    bdr:T192  a        bdo:Topic ;
       skos:altLabel   "gsan yig"@bo-x-ewts ;
       skos:prefLabel  "gsan yig"@bo-x-ewts , "thob yig"@bo-x-ewts , "record of teachings received"@en ;
       adm:gitRevision "bce3e1150c6e04399e4d9cf6ad2ec498a5392a92" ;
       adm:status      bdr:StatusReleased .

maybe this is related to [library #22](https://github.com/BuddhistDigitalResourceCenter/public-digital-library/issues/22)?

**Comment by eroux** [comment]
I can't reproduce this... maybe we can try again during the next migration?

**Comment by xristy** [comment]
Cannot reproduce. Closing.
