### ISSUE TITLE
importing withdrawn records

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#57]
I think we should decide how to represent withdrawn records and import the withdrawn records where we can parse the log string for the new record (usually "withdrawn in favor of...").

**Comment by xristy** [comment]
I agree that the withdrawn resources should be imported. Why not simply use:

    [] adm:status bdr:StatusWithdrawn

which can be filtered on as in the legacy system?

**Comment by eroux** [comment]
yes, we already have the properties so it should just be a matter of parsing the log strings

**Comment by eroux** [comment]
@xristy what's the correct property to indicate that an entity has been withdrawn as being a duplicate of another? there's `adm:replaceWithIndividual`, but it seems to be about individuals in vocabularies... ?

**Comment by xristy** [comment]
We can add `adm:replaceWith`: rdf:Resource ==> rdf:Resource which should allow to replace `:Person` by a `:Person` or a `:Topic` or an `:Event` or whatever is needed. `adm:replaceWithIndividual` can be made a subproperty.

**Comment by eroux** [comment]
sounds good!
