### ISSUE TITLE
better lang tag detection

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#58]
In some records like https://www.tbrc.org/xmldoc?rid=W1KG14618 there are strings with no lang tag indication that are in fact pinyin with no diacritics. They are currently tagged as `bo-x-ewts` but that's obviously wrong. Although we cannot detect that very accurately, the presence of an `x` is an indicator we could use.

**Comment by xristy** [comment]
We could run the ewts converter and produce a list ordered by the number of errors. The pinyin and other such strings should have high error rates. It would at least produce candidates to be looked at.

We may consider adding a Jena extension function for the ewts converter,

**Comment by eroux** [comment]
well... there's already a list [here](https://github.com/buda-base/library-issues/issues/23) but... I think we have to develop automation...

**Comment by xristy** [comment]
I was thinking of a sheet w/ resource URI, offending string, and number of errors detected by the ewts-converter. I'm thinking that there will be a largely bimodal distribution and that strings with large numbers of errors will not be as prevalent as the occasional errors in genuine bo-x-ewts.

I think the [list](https://github.com/buda-base/library-issues/issues/23) isn't as manageable as a sheet

**Comment by eroux** [comment]
Another example in https://www.tbrc.org/xmldoc?rid=W1GS61415

```xml
<w:catalogInfo encoding="extendedWylie" lang="tibetan">Biography of the famous Tibetan physician and scholar, Troru Tsenam.</w:catalogInfo>
```
