### ISSUE TITLE
bad ttl files generated

### ISSUE THREAD

**Issue by xristy** [buda-base/xmltoldmigration#66]
xmltoldmigration has output the following artifacts

./works/b7/ID.ttl

[works_b7_ID.ttl.zip](https://github.com/buda-base/xmltoldmigration/files/3024364/works_b7_ID.ttl.zip)

./works/b8/id.ttl

[works_b8_id.ttl.zip](https://github.com/buda-base/xmltoldmigration/files/3024366/works_b8_id.ttl.zip)

**Comment by eroux** [comment]
it doesn't seem to do that anymore
