### ISSUE TITLE
problems using git in xmltold... repos

### ISSUE THREAD

**Issue by xristy** [buda-base/xmltoldmigration#67]
Only some git commands work in the repos output by xmltold... Otheres do not work.

works:  `git log`, `git rm b7/ID.ttl`

doesn't work:  `git status`, `git commit`, `git add .` all hang

**Comment by eroux** [comment]
Can you zip a small git directory (roles maybe?) and attach it to the issue please?

**Comment by xristy** [comment]
The large repos apparently take a bunch of time to index or something similar. I just let `git status` run while I went away and it eventually returned and then git status and commit and add and so on work as they usually do - pretty much instantly.

Anyway now that I can use git commands I've `git rm`d the offending `id.ttl` and `ID.ttl` files and committed the changes and so now presumably the gittodbs will be able to get past that issue.

I'll just close this.
