### ISSUE TITLE
missing original records in Gretil records

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#72]
For instance

W0GR0244

is missing the information that the original is on

gretil.sub.uni-goettingen.de/#VasudhaDh_v1

**Comment by xristy** [comment]
to add to work bdo:originalRecord <gretil.sub.uni-goettingen.de/#VasudhaDh_v1>

**Comment by xristy** [comment]
fixed in [d35f1f0](https://github.com/buda-base/xmltoldmigration/commit/d35f1f09ee22fd18dd63459294cb74998d40af54)
