### ISSUE TITLE
two access objects in case of restricted in China?

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#79]
In case where a work is restricted in China, I think we should also add another value like `accessFairUse` or `accessOpen` (according to the license). This would allow the iiif servers to function better. wdyt?

**Comment by xristy** [comment]
I understand the issue and maybe having two access triples is good enough

**Comment by xristy** [comment]
fixed in [506f5c2](https://github.com/buda-base/xmltoldmigration/commit/506f5c2259b96cf6f66a61968124ff76d0e3113c)

**Comment by xristy** [comment]
I thought some more on it and have implemented:

```
adm:restrictedInChina :  adm:AdminData ==> xsd:boolean
```
where the `adm:AdminData` is for an `adm:Item`. Very simple to check for the restriction w/o have to deal w/ an _extra_ `adm:access` statement.

Implemented in [57882d5](https://github.com/buda-base/xmltoldmigration/commit/57882d5ef87562aae1bffa851a33c6ef1b0341b6)
