### ISSUE TITLE
Question about individuals graphs and bda: resources

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/xmltoldmigration#81]
Working in rdfc011rw dataset:

Let's consider `bdr:P1583` a "Real world resource" and `bda:CP035` , an admin resource

When I run `describe bdr:P1583` or `describe bda:CP035`, i get back triples data in both cases.

When I run `describe bda:P1583` I get data back (while there's no ` bdr:CP035`)

However, while I get the whole graph of P1583 when running:
`select * where { { graph bdg:P1583 {?s ?p ?o } }}`

I don't get anything when running:
`select * where { { graph bdg:CP035 {?s ?p ?o } }}`

Shouldn't there be a `bdg:CP035` ? or: don't we have "gr" such as
```
gr a adm:Graph ;
        adm:hasLegal bda:CP035 .
```

**Comment by xristy** [comment]
When I created these various kinds of _constants_ like `bda:CP035`, I did not fill in all the machinery like adm:adminAbout. I'm not going to do that now but after the rfc011 is finished I can contemplate it.

I didn't see having separate .trig files each of these, and git repos and so on, but I suppose that is what is needed for total consistency. This would I suppose mean removing all the files like access_types.ttl from the ontology and having no individuals in the ontology. This all makes me beyod tired!

This really an owl-schema issue since that's where these are defined.

**Comment by MarcAgate** [comment]
I have two minor concerns about individuals:

1) Are they editable (i.e can we create constants and edit them ?)
2) Serving various serialization of them (mainly from the ontology browsing web app)

but I suspect that for now, for case 1), we will favor owl-schema changes to create and edit Individuals and that in case 2) we can use `describe` instead of the graph based query.

**Comment by xristy** [comment]
I greatly do not want mess with the infrastructure of .ttl ontology files etc. 

Yes the _constants_ are editable in the ontology

We can add an `owl:Class`, `:Constant` and for each one of the various classes like `adm:Access` mark the individuals as `?s rdf:type :Constant`. This could be used as hint to ldspdi as to how to treat the resource for serialization and so on.

Does this help?

**Comment by MarcAgate** [comment]
As a matter of fact, if we don't deal with individuals in the ES, then we don't need to change or add anything to the ontology since ldspdi already knows (in the context of the ontology) that these bda:xxxx are Individuals of a given class.

**Comment by xristy** [comment]
How does "ldspdi already knows (in the context of the ontology) that these bda:xxxx are Individuals of a given class."?

**Comment by MarcAgate** [comment]
Through the OntModel class:
https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/ontology/OntModel.html

More specifically the two `listIndividuals() `methods

**Comment by xristy** [comment]
Excellent! So literally nothing do do except fix ldspdi to serve the little boogers

**Comment by eroux** [comment]
I think we can close it... any objection?

**Comment by MarcAgate** [comment]
go ahead !
