### ISSUE TITLE
typos etc.

### ISSUE THREAD

**Issue by berger-n** [buda-base/xmltoldmigration#93]
see http://purl.bdrc.io/resource/W8LS20123.ttl
it has `bdo:workObjectType  bdr:ObjectTypeBlockprint`
should be [`bdr:ObjectTypeBlockPrint`](http://purl.bdrc.io/resource/ObjectTypeBlockPrint.ttl)

**Comment by xristy** [comment]
Thx. The fix has been applied to the bdrcrw dataset. [W8LS20123](http://purl.bdrc.io/resource/W8LS20123.ttl) and others are now in sync w/ the ontology spelling

**Comment by berger-n** [comment]
see http://purl.bdrc.io/resource/WSAT_BCA.ttl
`bdo:workLangScript  bdo:ZhHant`
should be `bdo:ZhHant`
http://purl.bdrc.io/resource/ZhHant.ttl

**Comment by berger-n** [comment]
see http://library.bdrc.io/show/bdr:G1KR1884,
event http://purl.bdrc.io/resource/EVF08C2901B5C9.ttl is not displayed,
whereas http://purl.bdrc.io/resource/EVF08C2901B5C9.ttl is ;
difference is first one is `a bdo:Event`,
second one is `a  bdo:PlaceFounded` 
(tell me if it's not a data issue, I'll check the query)

**Comment by berger-n** [comment]
related to `:PlaceEvent` again
in http://library.bdrc.io/show/bdr:G3CN596 / http://purl.bdrc.io/resource/G3CN596.ttl
event http://purl.bdrc.io/resource/EV6B1858360B60.ttl is `bdo:PlaceEventTypeNotSpecified`
should be `do:PlaceEventNotSpecified`
(https://github.com/buda-base/owl-schema/blob/29af70cf7384da8047809e134d0ade52f4820a71/core/bdo.ttl#L1050)

**Comment by berger-n** [comment]
thanks!
