### ISSUE TITLE
bdo:PersonGrammatical

### ISSUE THREAD

**Issue by berger-n** [buda-base/xmltoldmigration#95]
in http://purl.bdrc.io/resource/P196.ttl / http://library.bdrc.io/show/bdr:P196
there is a `bdo:PersonName` which is a `bdo:PersonGrammatical` : http://purl.bdrc.io/resource/NM11CE85FEA920.ttl
does not seem to be a valid  http://purl.bdrc.io/ontology/core/PersonName

**Comment by eroux** [comment]
haha, that's a funny one! it's in the data though: http://tbrc.org/xmldoc?rid=P196

**Comment by xristy** [comment]
`P196` fixed in tbrc.org data. Changed `grammatical` to `personalName`. Correction will appear with net update tomorrow morning
