### ISSUE TITLE
don't do empty commits

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#96]
I was walking through the data on gitlab and saw that:

https://gitlab.com/bdrc-data/persons/commit/e3b23ab7e993aa58384fc4866579d62942420aff

which is a commit by xmltold with no difference. I didn't know there was such a thing as an empty commit (and that's the assumption made by xmltold too). Turns out there is! We should make sure that commits by xlmtold are not empty, that will make our data much easier to navigate

**Comment by MarcAgate** [comment]
GitHelpers has been modified so it doesn't commit when there are no changes. See https://github.com/buda-base/bdrc-libraries/commit/edcb32ea5b45220cf3f742dad77540bf1ed03685
