### ISSUE TITLE
use of properties undeclared in ontology

### ISSUE THREAD

**Issue by berger-n** [buda-base/xmltoldmigration#97]
http://purl.bdrc.io/resource/NM5264C00FA151.ttl
seen here: http://library.bdrc.io/show/bdr:P6002 
(original record: https://www.tbrc.org/xmldoc?rid=P6002)

**Comment by berger-n** [comment]
similar issue with bdo:PersonReversal
http://purl.bdrc.io/resource/NM68EE3382A105.ttl
seen here:http://purl.bdrc.io/resource/P1.ttl
(original xml: https://www.tbrc.org/xmldoc?rid=P1)

I mean `bdo:PersonVariantOrthography` and `bdo:PersonReversal` are used in data
but don't exist in ontology

I should change the 100% unclear issue title 
and maybe report it in owl-schema ?

**Comment by xristy** [comment]
fixed in owl-schema [commit 3580e48](https://github.com/buda-base/owl-schema/commit/3580e487c487f2441c2e0c257aec2d326cdc84cd). Added `:PersonReversal` and `:PersonVariantOrthography`

**Comment by berger-n** [comment]
Thanks!
